
BUZZ("AGAIN", "G", "OOPS")
BUZZ("A", "AN", "THE", "IS", "AND", "OF", "THEN", "ALL", "ONE", "BUT", "EXCEPT", "YES", "NO", "Y", "HERE")

if   EQUALQ(ZORK_NUMBER, 2) then 
  BUZZ("FEEBLE", "FUMBLE", "FEAR", "FILCH", "FREEZE", "FALL", "FRY", "FLUORESCE", "FERMENT", "FIERCE", "FLOAT", "FIREPROOF", "FENCE", "FUDGE", "FANTASIZE", "FROTZ", "OZMOO")

elseif   EQUALQ(ZORK_NUMBER, 3) then 
  BUZZ("FROTZ", "OZMOO")

end
BUZZ("WITH", "USING", "THROUGH", "THRU")
BUZZ("IN", "INSIDE", "INTO")
BUZZ("ON", "ONTO")
BUZZ("UNDER", "UNDERNEATH", "BENEATH", "BELOW")
BUZZ("NORTH", "N")
BUZZ("SOUTH", "S")
BUZZ("EAST", "E")
BUZZ("WEST", "W")
BUZZ("DOWN", "D")
BUZZ("UP", "U")
BUZZ("NW", "NORTHWEST")
BUZZ("NE", "NORTHE")
BUZZ("SW", "SOUTHWEST")
BUZZ("SE", "SOUTHE")
SYNTAX {
	VERB = "VERBOSE",
	ACTION = V_VERBOSE,
}
SYNTAX {
	VERB = "BRIEF",
	ACTION = V_BRIEF,
}
SYNTAX {
	VERB = "SUPER",
	ACTION = V_SUPER_BRIEF,
}
BUZZ("SUPER", "SUPERBRIEF")
SYNTAX {
	VERB = "DIAGNOSE",
	ACTION = V_DIAGNOSE,
}
SYNTAX {
	VERB = "INVENTORY",
	ACTION = V_INVENTORY,
}
BUZZ("INVENTORY", "I")
SYNTAX {
	VERB = "QUIT",
	ACTION = V_QUIT,
}
BUZZ("QUIT", "Q")
SYNTAX {
	VERB = "RESTART",
	ACTION = V_RESTART,
}
SYNTAX {
	VERB = "RESTORE",
	ACTION = V_RESTORE,
}
SYNTAX {
	VERB = "SAVE",
	ACTION = V_SAVE,
}
SYNTAX {
	VERB = "SCORE",
	ACTION = V_SCORE,
}
SYNTAX {
	VERB = "SCRIPT",
	ACTION = V_SCRIPT,
}
SYNTAX {
	VERB = "UNSCRIPT",
	ACTION = V_UNSCRIPT,
}
SYNTAX {
	VERB = "VERSION",
	ACTION = V_VERSION,
}
SYNTAX {
	VERB = "$VERIFY",
	ACTION = V_VERIFY,
}
SYNTAX {
	VERB = "RANDOM",
	OBJECT = {
	},
	ACTION = V_RANDOM,
}
SYNTAX {
	VERB = "COMMAND",
	ACTION = V_COMMAND_FILE,
}
SYNTAX {
	VERB = "RECORD",
	ACTION = V_RECORD,
}
SYNTAX {
	VERB = "UNRECORD",
	ACTION = V_UNRECORD,
}
SYNTAX {
	VERB = "ACTIVATE",
	OBJECT = {
		FIND = LIGHTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_LAMP_ON,
}
SYNTAX {
	VERB = "ANSWER",
	ACTION = V_ANSWER,
}
SYNTAX {
	VERB = "ANSWER",
	OBJECT = {
	},
	ACTION = V_REPLY,
}
BUZZ("ANSWER", "REPLY")
SYNTAX {
	VERB = "APPLY",
	OBJECT = {
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_PUT,
}

if   EQUALQ(ZORK_NUMBER, 2) then 
  SYNTAX {
	VERB = "ATTACK",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ATTACK,
}

end
SYNTAX {
	VERB = "ATTACK",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_ATTACK,
}
BUZZ("ATTACK", "FIGHT", "HURT", "INJURE", "HIT")
SYNTAX {
	VERB = "BACK",
	ACTION = V_BACK,
}
SYNTAX {
	VERB = "BLAST",
	ACTION = V_BLAST,
}
SYNTAX {
	VERB = "BLOW OUT",
	OBJECT = {
	},
	ACTION = V_LAMP_OFF,
}
SYNTAX {
	VERB = "BLOW UP",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	ACTION = V_INFLATE,
}
SYNTAX {
	VERB = "BLOW UP",
	OBJECT = {
	},
	ACTION = V_BLAST,
}
SYNTAX {
	VERB = "BLOW IN",
	OBJECT = {
	},
	ACTION = V_BREATHE,
}
SYNTAX {
	VERB = "BOARD",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_BOARD,
}
SYNTAX {
	VERB = "BRUSH",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_BRUSH,
}
SYNTAX {
	VERB = "BRUSH",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_BRUSH,
}
BUZZ("BRUSH", "CLEAN")
SYNTAX {
	VERB = "BUG",
	ACTION = V_BUG,
}
SYNTAX {
	VERB = "BURN",
	OBJECT = {
		FIND = BURNBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = FLAMEBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","HAVE",},
	},
	ACTION = V_BURN,
}
SYNTAX {
	VERB = "BURN DOWN",
	OBJECT = {
		FIND = BURNBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = FLAMEBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","HAVE",},
	},
	ACTION = V_BURN,
}
BUZZ("BURN", "INCINERATE", "IGNITE")
SYNTAX {
	VERB = "CHOMP",
	ACTION = V_CHOMP,
}
BUZZ("CHOMP", "LOSE", "BARF")
SYNTAX {
	VERB = "CLIMB UP",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_CLIMB_UP,
}
SYNTAX {
	VERB = "CLIMB UP",
	OBJECT = {
		FIND = CLIMBBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_UP,
}
SYNTAX {
	VERB = "CLIMB DOWN",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_CLIMB_DOWN,
}
SYNTAX {
	VERB = "CLIMB DOWN",
	OBJECT = {
		FIND = CLIMBBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_DOWN,
}
SYNTAX {
	VERB = "CLIMB",
	OBJECT = {
		FIND = CLIMBBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_FOO,
}
SYNTAX {
	VERB = "CLIMB IN",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_BOARD,
}
SYNTAX {
	VERB = "CLIMB ON",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_ON,
}
SYNTAX {
	VERB = "CLIMB WITH",
	OBJECT = {
	},
	ACTION = V_THROUGH,
}
BUZZ("CLIMB", "SIT")
SYNTAX {
	VERB = "CLOSE",
	OBJECT = {
		FIND = DOORBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLOSE,
}
SYNTAX {
	VERB = "COMMAND",
	OBJECT = {
		FIND = ACTORBIT,
	},
	ACTION = V_COMMAND,
}
SYNTAX {
	VERB = "COUNT",
	OBJECT = {
	},
	ACTION = V_COUNT,
}
SYNTAX {
	VERB = "CROSS",
	OBJECT = {
	},
	ACTION = V_CROSS,
}
BUZZ("CROSS", "FORD")
SYNTAX {
	VERB = "CUT",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"CARRIED","HELD",},
	},
	ACTION = V_CUT,
}
BUZZ("CUT", "SLICE", "PIERCE")
SYNTAX {
	VERB = "CURSE",
	ACTION = V_CURSES,
}
SYNTAX {
	VERB = "CURSE",
	OBJECT = {
		FIND = ACTORBIT,
	},
	ACTION = V_CURSES,
}
BUZZ("CURSE", "SHIT", "FUCK", "DAMN")
SYNTAX {
	VERB = "DEFLATE",
	OBJECT = {
	},
	ACTION = V_DEFLATE,
}
SYNTAX {
	VERB = "DESTROY",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	JOIN = "WITH",
	SUBJECT = {
		WHERE = {"HELD","CARRIED","TAKE",},
	},
	ACTION = V_MUNG,
}
SYNTAX {
	VERB = "DESTROY DOWN",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	JOIN = "WITH",
	SUBJECT = {
		WHERE = {"HELD","CARRIED","TAKE",},
	},
	ACTION = V_MUNG,
}
SYNTAX {
	VERB = "DESTROY IN",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	ACTION = V_OPEN,
}
BUZZ("DESTROY", "DAMAGE", "BREAK", "BLOCK", "SMASH")
SYNTAX {
	VERB = "DIG IN",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_DIG,
}
SYNTAX {
	VERB = "DIG IN",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_DIG,
}
SYNTAX {
	VERB = "DIG",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_DIG,
}
SYNTAX {
	VERB = "DISEMBARK",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_DISEMBARK,
}
SYNTAX {
	VERB = "DISENCHANT",
	OBJECT = {
	},
	ACTION = V_DISENCHANT,
}
SYNTAX {
	VERB = "DRINK",
	OBJECT = {
		FIND = DRINKBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_DRINK,
}
SYNTAX {
	VERB = "DRINK FROM",
	OBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	ACTION = V_DRINK_FROM,
}
BUZZ("DRINK", "IMBIBE", "SWALLOW")
SYNTAX {
	VERB = "DROP",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	ACTION = V_DROP,
}
SYNTAX {
	VERB = "DROP",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "DOWN",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "DROP",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "IN",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "DROP",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_PUT_ON,
}
SYNTAX {
	VERB = "EAT",
	OBJECT = {
		FIND = FOODBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	ACTION = V_EAT,
}
BUZZ("EAT", "CONSUME", "TASTE", "BITE")
SYNTAX {
	VERB = "ECHO",
	ACTION = V_ECHO,
}
SYNTAX {
	VERB = "ENCHANT",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ENCHANT,
}
SYNTAX {
	VERB = "ENTER",
	ACTION = V_ENTER,
}
SYNTAX {
	VERB = "ENTER",
	OBJECT = {
	},
	ACTION = V_THROUGH,
}
SYNTAX {
	VERB = "EXIT",
	ACTION = V_EXIT,
}
SYNTAX {
	VERB = "EXIT",
	OBJECT = {
	},
	ACTION = V_EXIT,
}
SYNTAX {
	VERB = "EXAMINE",
	OBJECT = {
		WHERE = {"MANY",},
	},
	ACTION = V_EXAMINE,
}
SYNTAX {
	VERB = "EXAMINE IN",
	OBJECT = {
		WHERE = {"HELD","CARRIED","IN_ROOM","ON_GROUND","MANY",},
	},
	ACTION = V_LOOK_INSIDE,
}
SYNTAX {
	VERB = "EXAMINE ON",
	OBJECT = {
		WHERE = {"HELD","CARRIED","IN_ROOM","ON_GROUND","MANY",},
	},
	ACTION = V_LOOK_INSIDE,
}
BUZZ("EXAMINE", "DESCRIBE", "WHAT", "WHATS")
SYNTAX {
	VERB = "EXORCISE",
	OBJECT = {
	},
	ACTION = V_EXORCISE,
}
SYNTAX {
	VERB = "EXORCISE OUT",
	OBJECT = {
		FIND = ACTORBIT,
	},
	ACTION = V_EXORCISE,
}
SYNTAX {
	VERB = "EXORCISE AWAY",
	OBJECT = {
		FIND = ACTORBIT,
	},
	ACTION = V_EXORCISE,
}
BUZZ("EXORCISE", "BANISH", "CAST", "DRIVE", "BEGONE")
SYNTAX {
	VERB = "EXTINGUISH",
	OBJECT = {
		FIND = ONBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE","HAVE",},
	},
	ACTION = V_LAMP_OFF,
}
BUZZ("EXTINGUISH", "DOUSE")
SYNTAX {
	VERB = "FILL",
	OBJECT = {
		FIND = CONTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_FILL,
}
SYNTAX {
	VERB = "FILL",
	OBJECT = {
		FIND = CONTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_FILL,
}
SYNTAX {
	VERB = "FIND",
	OBJECT = {
	},
	ACTION = V_FIND,
}
BUZZ("FIND", "WHERE", "SEEK", "SEE")
SYNTAX {
	VERB = "FOLLOW",
	ACTION = V_FOLLOW,
}
SYNTAX {
	VERB = "FOLLOW",
	OBJECT = {
	},
	ACTION = V_FOLLOW,
}
BUZZ("FOLLOW", "PURSUE", "CHASE", "COME")
SYNTAX {
	VERB = "FROBOZZ",
	ACTION = V_FROBOZZ,
}
SYNTAX {
	VERB = "GIVE",
	OBJECT = {
		WHERE = {"MANY","HELD","HAVE",},
	},
	JOIN = "TO",
	SUBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND",},
	},
	ACTION = V_GIVE,
}
SYNTAX {
	VERB = "GIVE",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND",},
	},
	SUBJECT = {
		WHERE = {"MANY","HELD","HAVE",},
	},
	ACTION = V_SGIVE,
}
BUZZ("GIVE", "DONATE", "OFFER", "FEED")

if   NEQUALQ(ZORK_NUMBER, 3) then 
  BUZZ("GIVE", "HAND")

end
SYNTAX {
	VERB = "HATCH",
	OBJECT = {
	},
	ACTION = V_HATCH,
}
SYNTAX {
	VERB = "HELLO",
	ACTION = V_HELLO,
}
SYNTAX {
	VERB = "HELLO",
	OBJECT = {
	},
	ACTION = V_HELLO,
}
BUZZ("HELLO", "HI")
SYNTAX {
	VERB = "INCANT",
	ACTION = V_INCANT,
}
BUZZ("INCANT", "CHANT")
SYNTAX {
	VERB = "INFLAT",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	ACTION = V_INFLATE,
}
SYNTAX {
	VERB = "JUMP",
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "JUMP OVER",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "JUMP ACROSS",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "JUMP IN",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "JUMP FROM",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "JUMP OFF",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
BUZZ("JUMP", "LEAP", "DIVE")
SYNTAX {
	VERB = "KICK",
	OBJECT = {
	},
	ACTION = V_KICK,
}
BUZZ("KICK", "TAUNT")

if   EQUALQ(ZORK_NUMBER, 2) then 
  SYNTAX {
	VERB = "KILL",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ATTACK,
}

end
SYNTAX {
	VERB = "KILL",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_ATTACK,
}
BUZZ("KILL", "MURDER", "SLAY", "DISPATCH")
SYNTAX {
	VERB = "STAB",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_STAB,
}
SYNTAX {
	VERB = "STAB",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_ATTACK,
}
SYNTAX {
	VERB = "KISS",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_KISS,
}
SYNTAX {
	VERB = "KNOCK AT",
	OBJECT = {
	},
	ACTION = V_KNOCK,
}
SYNTAX {
	VERB = "KNOCK ON",
	OBJECT = {
	},
	ACTION = V_KNOCK,
}
SYNTAX {
	VERB = "KNOCK DOWN",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ATTACK,
}
BUZZ("KNOCK", "RAP")
SYNTAX {
	VERB = "LAUNCH",
	OBJECT = {
		FIND = VEHBIT,
	},
	ACTION = V_LAUNCH,
}
SYNTAX {
	VERB = "LEAN ON",
	OBJECT = {
		WHERE = {"HELD","HAVE",},
	},
	ACTION = V_LEAN_ON,
}
SYNTAX {
	VERB = "LEAVE",
	ACTION = V_LEAVE,
}
SYNTAX {
	VERB = "LEAVE",
	OBJECT = {
	},
	ACTION = V_DROP,
}
SYNTAX {
	VERB = "LIGHT",
	OBJECT = {
		FIND = LIGHTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE","HAVE",},
	},
	ACTION = V_LAMP_ON,
}
SYNTAX {
	VERB = "LIGHT",
	OBJECT = {
		FIND = LIGHTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = FLAMEBIT,
		WHERE = {"HELD","CARRIED","TAKE","HAVE",},
	},
	ACTION = V_BURN,
}
SYNTAX {
	VERB = "LISTEN TO",
	OBJECT = {
	},
	ACTION = V_LISTEN,
}
SYNTAX {
	VERB = "LISTEN FOR",
	OBJECT = {
	},
	ACTION = V_LISTEN,
}
SYNTAX {
	VERB = "LOCK",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	ACTION = V_LOCK,
}
SYNTAX {
	VERB = "LOOK",
	ACTION = V_LOOK,
}
SYNTAX {
	VERB = "LOOK AROUND",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_LOOK,
}
SYNTAX {
	VERB = "LOOK UP",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_LOOK,
}
SYNTAX {
	VERB = "LOOK DOWN",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_LOOK,
}
SYNTAX {
	VERB = "LOOK AT",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","MANY",},
	},
	ACTION = V_EXAMINE,
}
SYNTAX {
	VERB = "LOOK ON",
	OBJECT = {
	},
	ACTION = V_LOOK_ON,
}
SYNTAX {
	VERB = "LOOK WITH",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","MANY",},
	},
	ACTION = V_LOOK_INSIDE,
}
SYNTAX {
	VERB = "LOOK UNDER",
	OBJECT = {
	},
	ACTION = V_LOOK_UNDER,
}
SYNTAX {
	VERB = "LOOK BEHIND",
	OBJECT = {
	},
	ACTION = V_LOOK_BEHIND,
}
SYNTAX {
	VERB = "LOOK IN",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","MANY",},
	},
	ACTION = V_LOOK_INSIDE,
}
SYNTAX {
	VERB = "LOOK AT",
	OBJECT = {
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_READ,
}
SYNTAX {
	VERB = "LOOK FOR",
	OBJECT = {
	},
	ACTION = V_FIND,
}
BUZZ("LOOK", "L", "STARE", "GAZE")
SYNTAX {
	VERB = "LOWER",
	OBJECT = {
	},
	ACTION = V_LOWER,
}
SYNTAX {
	VERB = "LUBRICATE",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	ACTION = V_OIL,
}
BUZZ("LUBRICATE", "OIL", "GREASE")
SYNTAX {
	VERB = "MAKE",
	OBJECT = {
	},
	ACTION = V_MAKE,
}
SYNTAX {
	VERB = "MELT",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = FLAMEBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MELT,
}
BUZZ("MELT", "LIQUIFY")
SYNTAX {
	VERB = "MOVE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
SYNTAX {
	VERB = "MOVE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "MOVE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "MOVE",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "IN",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "MOVE",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
	},
	ACTION = V_TURN,
}
SYNTAX {
	VERB = "ROLL UP",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
SYNTAX {
	VERB = "ROLL",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
SYNTAX {
	VERB = "MUMBLE",
	ACTION = V_MUMBLE,
}
BUZZ("MUMBLE", "SIGH")
SYNTAX {
	VERB = "ODYSSEUS",
	ACTION = V_ODYSSEUS,
}
BUZZ("ODYSSEUS", "ULYSSES")
SYNTAX {
	VERB = "OPEN",
	OBJECT = {
		FIND = DOORBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_OPEN,
}
SYNTAX {
	VERB = "OPEN UP",
	OBJECT = {
		FIND = DOORBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_OPEN,
}
SYNTAX {
	VERB = "OPEN",
	OBJECT = {
		FIND = DOORBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED","HAVE",},
	},
	ACTION = V_OPEN,
}
SYNTAX {
	VERB = "PICK",
	OBJECT = {
	},
	ACTION = V_PICK,
}
SYNTAX {
	VERB = "PICK",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_PICK,
}
SYNTAX {
	VERB = "PICK UP",
	OBJECT = {
		FIND = TAKEBIT,
		WHERE = {"ON_GROUND","MANY",},
	},
	ACTION = V_TAKE,
}
SYNTAX {
	VERB = "PLAY",
	OBJECT = {
	},
	ACTION = V_PLAY,
}
SYNTAX {
	VERB = "PLUG",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_PLUG,
}
BUZZ("PLUG", "GLUE", "PATCH", "REPAIR", "FIX")
SYNTAX {
	VERB = "PLUGH",
	ACTION = V_ADVENT,
}
BUZZ("PLUGH", "XYZZY")
SYNTAX {
	VERB = "POKE",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_MUNG,
}
SYNTAX {
	VERB = "PUNCTURE",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_MUNG,
}
SYNTAX {
	VERB = "POUR",
	OBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	ACTION = V_DROP,
}
SYNTAX {
	VERB = "POUR",
	OBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	JOIN = "IN",
	SUBJECT = {
	},
	ACTION = V_DROP,
}
SYNTAX {
	VERB = "POUR",
	OBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_POUR_ON,
}
SYNTAX {
	VERB = "POUR",
	OBJECT = {
		WHERE = {"HELD","CARRIED",},
	},
	JOIN = "FROM",
	SUBJECT = {
	},
	ACTION = V_DROP,
}
BUZZ("POUR", "SPILL")
SYNTAX {
	VERB = "PRAY",
	ACTION = V_PRAY,
}
SYNTAX {
	VERB = "PULL",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
SYNTAX {
	VERB = "PULL ON",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
SYNTAX {
	VERB = "PULL UP",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_MOVE,
}
BUZZ("PULL", "TUG", "YANK")
SYNTAX {
	VERB = "PUMP UP",
	OBJECT = {
	},
	ACTION = V_PUMP,
}
SYNTAX {
	VERB = "PUMP UP",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_PUMP,
}
SYNTAX {
	VERB = "PUSH",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND",},
	},
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "PUSH",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND",},
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "PUSH",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND","MANY",},
	},
	ACTION = V_PUSH,
}
SYNTAX {
	VERB = "PUSH ON",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND","MANY",},
	},
	ACTION = V_PUSH,
}
SYNTAX {
	VERB = "PUSH",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
	},
	ACTION = V_TURN,
}
SYNTAX {
	VERB = "PUSH",
	OBJECT = {
	},
	JOIN = "UNDER",
	SUBJECT = {
	},
	ACTION = V_PUT_UNDER,
}
BUZZ("PUSH", "PRESS")
SYNTAX {
	VERB = "PUT",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "IN",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "PUT",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_PUT_ON,
}
SYNTAX {
	VERB = "PUT DOWN",
	OBJECT = {
		WHERE = {"HELD","MANY",},
	},
	ACTION = V_DROP,
}
SYNTAX {
	VERB = "PUT",
	OBJECT = {
		WHERE = {"HELD","HAVE",},
	},
	JOIN = "UNDER",
	SUBJECT = {
	},
	ACTION = V_PUT_UNDER,
}
SYNTAX {
	VERB = "PUT OUT",
	OBJECT = {
		FIND = ONBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE","HAVE",},
	},
	ACTION = V_LAMP_OFF,
}
SYNTAX {
	VERB = "PUT ON",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND","CARRIED","MANY",},
	},
	ACTION = V_WEAR,
}
SYNTAX {
	VERB = "PUT",
	OBJECT = {
		WHERE = {"HELD","MANY","HAVE",},
	},
	JOIN = "BEHIND",
	SUBJECT = {
	},
	ACTION = V_PUT_BEHIND,
}
BUZZ("PUT", "STUFF", "INSERT", "PLACE", "HIDE")
SYNTAX {
	VERB = "RAISE",
	OBJECT = {
	},
	ACTION = V_RAISE,
}
SYNTAX {
	VERB = "RAISE UP",
	OBJECT = {
	},
	ACTION = V_RAISE,
}
BUZZ("RAISE", "LIFT")
SYNTAX {
	VERB = "RAPE",
	OBJECT = {
		FIND = ACTORBIT,
	},
	ACTION = V_RAPE,
}
BUZZ("RAPE", "MOLEST")
SYNTAX {
	VERB = "READ",
	OBJECT = {
		FIND = READBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	ACTION = V_READ,
}
SYNTAX {
	VERB = "READ FROM",
	OBJECT = {
		FIND = READBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	ACTION = V_READ,
}
SYNTAX {
	VERB = "READ",
	OBJECT = {
		FIND = READBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_READ,
}
SYNTAX {
	VERB = "READ",
	OBJECT = {
		FIND = READBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	SUBJECT = {
	},
	ACTION = V_READ_PAGE,
}
BUZZ("READ", "SKIM")
SYNTAX {
	VERB = "REPENT",
	ACTION = V_REPENT,
}
SYNTAX {
	VERB = "RING",
	OBJECT = {
		WHERE = {"TAKE",},
	},
	ACTION = V_RING,
}
SYNTAX {
	VERB = "RING",
	OBJECT = {
		WHERE = {"TAKE",},
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_RING,
}
BUZZ("RING", "PEAL")
SYNTAX {
	VERB = "RUB",
	OBJECT = {
	},
	ACTION = V_RUB,
}
SYNTAX {
	VERB = "RUB",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_RUB,
}
BUZZ("RUB", "TOUCH", "FEEL", "PAT", "PET")
SYNTAX {
	VERB = "TALK TO",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"IN_ROOM",},
	},
	ACTION = V_TELL,
}
SYNTAX {
	VERB = "SAY",
	ACTION = V_SAY,
}
SYNTAX {
	VERB = "SEARCH",
	OBJECT = {
	},
	ACTION = V_SEARCH,
}
SYNTAX {
	VERB = "SEARCH IN",
	OBJECT = {
	},
	ACTION = V_SEARCH,
}
SYNTAX {
	VERB = "SEARCH FOR",
	OBJECT = {
	},
	ACTION = V_FIND,
}
SYNTAX {
	VERB = "SEND FOR",
	OBJECT = {
	},
	ACTION = V_SEND,
}
SYNTAX {
	VERB = "SHAKE",
	OBJECT = {
		WHERE = {"HAVE",},
	},
	ACTION = V_SHAKE,
}
SYNTAX {
	VERB = "SKIP",
	ACTION = V_SKIP,
}
BUZZ("SKIP", "HOP")
SYNTAX {
	VERB = "SLIDE",
	OBJECT = {
	},
	JOIN = "UNDER",
	SUBJECT = {
	},
	ACTION = V_PUT_UNDER,
}
SYNTAX {
	VERB = "SLIDE",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND",},
	},
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "SLIDE",
	OBJECT = {
		WHERE = {"IN_ROOM","ON_GROUND",},
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_PUSH_TO,
}
SYNTAX {
	VERB = "SMELL",
	OBJECT = {
	},
	ACTION = V_SMELL,
}
BUZZ("SMELL", "SNIFF")
SYNTAX {
	VERB = "SPIN",
	OBJECT = {
	},
	ACTION = V_SPIN,
}
SYNTAX {
	VERB = "SPRAY",
	OBJECT = {
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_SPRAY,
}
SYNTAX {
	VERB = "SPRAY",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
	},
	ACTION = V_SSPRAY,
}
SYNTAX {
	VERB = "SQUEEZE",
	OBJECT = {
	},
	ACTION = V_SQUEEZE,
}
SYNTAX {
	VERB = "SQUEEZE",
	OBJECT = {
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "STAND",
	ACTION = V_STAND,
}
SYNTAX {
	VERB = "STAND UP",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_STAND,
}
SYNTAX {
	VERB = "STAY",
	ACTION = V_STAY,
}
SYNTAX {
	VERB = "STRIKE",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","HAVE",},
	},
	ACTION = V_ATTACK,
}
SYNTAX {
	VERB = "STRIKE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	ACTION = V_STRIKE,
}
SYNTAX {
	VERB = "SWIM",
	ACTION = V_SWIM,
}
SYNTAX {
	VERB = "SWIM IN",
	OBJECT = {
	},
	ACTION = V_SWIM,
}
SYNTAX {
	VERB = "SWIM ACROSS",
	OBJECT = {
	},
	ACTION = V_SWIM,
}
BUZZ("SWIM", "BATHE", "WADE")
SYNTAX {
	VERB = "SWING",
	OBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	ACTION = V_SWING,
}
SYNTAX {
	VERB = "SWING",
	OBJECT = {
		FIND = WEAPONBIT,
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "AT",
	SUBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_SWING,
}
BUZZ("SWING", "THRUST")
SYNTAX {
	VERB = "TAKE",
	OBJECT = {
		FIND = TAKEBIT,
		WHERE = {"ON_GROUND","IN_ROOM","MANY",},
	},
	ACTION = V_TAKE,
}
SYNTAX {
	VERB = "TAKE IN",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_BOARD,
}
SYNTAX {
	VERB = "TAKE OUT",
	OBJECT = {
		FIND = RMUNGBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_DISEMBARK,
}
SYNTAX {
	VERB = "TAKE ON",
	OBJECT = {
		FIND = VEHBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_ON,
}
SYNTAX {
	VERB = "TAKE UP",
	OBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_STAND,
}
SYNTAX {
	VERB = "TAKE",
	OBJECT = {
		FIND = TAKEBIT,
		WHERE = {"CARRIED","IN_ROOM","MANY",},
	},
	JOIN = "OUT",
	SUBJECT = {
	},
	ACTION = V_TAKE,
}
SYNTAX {
	VERB = "TAKE",
	OBJECT = {
		FIND = TAKEBIT,
		WHERE = {"CARRIED","IN_ROOM","MANY",},
	},
	JOIN = "OFF",
	SUBJECT = {
	},
	ACTION = V_TAKE,
}
SYNTAX {
	VERB = "TAKE",
	OBJECT = {
		FIND = TAKEBIT,
		WHERE = {"IN_ROOM","CARRIED","MANY",},
	},
	JOIN = "FROM",
	SUBJECT = {
	},
	ACTION = V_TAKE,
}
BUZZ("TAKE", "GET", "HOLD", "CARRY", "REMOVE", "GRAB", "CATCH")
SYNTAX {
	VERB = "TELL",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"IN_ROOM",},
	},
	ACTION = V_TELL,
}
SYNTAX {
	VERB = "TELL",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"IN_ROOM",},
	},
	JOIN = "ABOUT",
	SUBJECT = {
	},
	ACTION = V_TELL,
}
BUZZ("TELL", "ASK")
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "AT",
	SUBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_THROW,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_THROW,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
	},
	SUBJECT = {
	},
	ACTION = V_OVERBOARD,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "IN",
	SUBJECT = {
	},
	ACTION = V_PUT,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "ON",
	SUBJECT = {
	},
	ACTION = V_PUT_ON,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "OFF",
	SUBJECT = {
	},
	ACTION = V_THROW_OFF,
}
SYNTAX {
	VERB = "THROW",
	OBJECT = {
		WHERE = {"HELD","CARRIED","HAVE",},
	},
	JOIN = "OVER",
	SUBJECT = {
	},
	ACTION = V_THROW_OFF,
}
BUZZ("THROW", "HURL", "CHUCK", "TOSS")
SYNTAX {
	VERB = "TIE",
	OBJECT = {
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_TIE,
}
SYNTAX {
	VERB = "TIE UP",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED","HAVE",},
	},
	ACTION = V_TIE_UP,
}
BUZZ("TIE", "FASTEN", "SECURE", "ATTACH")
SYNTAX {
	VERB = "TREASURE",
	ACTION = V_TREASURE,
}
BUZZ("TREASURE", "TEMPLE")
SYNTAX {
	VERB = "TURN",
	OBJECT = {
		FIND = TURNBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = RMUNGBIT,
	},
	ACTION = V_TURN,
}
SYNTAX {
	VERB = "TURN ON",
	OBJECT = {
		FIND = LIGHTBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM",},
	},
	ACTION = V_LAMP_ON,
}
SYNTAX {
	VERB = "TURN ON",
	OBJECT = {
	},
	JOIN = "WITH",
	SUBJECT = {
		WHERE = {"HAVE",},
	},
	ACTION = V_LAMP_ON,
}
SYNTAX {
	VERB = "TURN OFF",
	OBJECT = {
		FIND = ONBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE","HAVE",},
	},
	ACTION = V_LAMP_OFF,
}
SYNTAX {
	VERB = "TURN",
	OBJECT = {
		FIND = TURNBIT,
	},
	JOIN = "TO",
	SUBJECT = {
	},
	ACTION = V_TURN,
}
SYNTAX {
	VERB = "TURN",
	OBJECT = {
		FIND = TURNBIT,
	},
	JOIN = "FOR",
	SUBJECT = {
	},
	ACTION = V_TURN,
}
BUZZ("TURN", "SET", "FLIP", "SHUT")
SYNTAX {
	VERB = "UNLOCK",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	JOIN = "WITH",
	SUBJECT = {
		FIND = TOOLBIT,
		WHERE = {"HELD","CARRIED","ON_GROUND","IN_ROOM","TAKE",},
	},
	ACTION = V_UNLOCK,
}
SYNTAX {
	VERB = "UNTIE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	ACTION = V_UNTIE,
}
SYNTAX {
	VERB = "UNTIE",
	OBJECT = {
		WHERE = {"ON_GROUND","IN_ROOM","HELD","CARRIED",},
	},
	JOIN = "FROM",
	SUBJECT = {
	},
	ACTION = V_UNTIE,
}
BUZZ("UNTIE", "FREE", "RELEASE", "UNFASTEN", "UNATTACH", "UNHOOK")
SYNTAX {
	VERB = "WAIT",
	ACTION = V_WAIT,
}
BUZZ("WAIT", "Z")
SYNTAX {
	VERB = "WAKE",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ALARM,
}
SYNTAX {
	VERB = "WAKE UP",
	OBJECT = {
		FIND = ACTORBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_ALARM,
}
BUZZ("WAKE", "AWAKE", "SURPRISE", "STARTLE")
SYNTAX {
	VERB = "WALK",
	ACTION = V_WALK_AROUND,
}
SYNTAX {
	VERB = "WALK",
	OBJECT = {
	},
	ACTION = V_WALK,
}
SYNTAX {
	VERB = "WALK AWAY",
	OBJECT = {
	},
	ACTION = V_WALK,
}
SYNTAX {
	VERB = "WALK IN",
	OBJECT = {
	},
	ACTION = V_THROUGH,
}
SYNTAX {
	VERB = "WALK WITH",
	OBJECT = {
	},
	ACTION = V_THROUGH,
}
SYNTAX {
	VERB = "WALK ON",
	OBJECT = {
	},
	ACTION = V_THROUGH,
}
SYNTAX {
	VERB = "WALK OVER",
	OBJECT = {
	},
	ACTION = V_LEAP,
}
SYNTAX {
	VERB = "WALK TO",
	OBJECT = {
	},
	ACTION = V_WALK_TO,
}
SYNTAX {
	VERB = "WALK AROUND",
	OBJECT = {
	},
	ACTION = V_WALK_AROUND,
}
SYNTAX {
	VERB = "WALK UP",
	OBJECT = {
		FIND = CLIMBBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_UP,
}
SYNTAX {
	VERB = "WALK DOWN",
	OBJECT = {
		FIND = CLIMBBIT,
		WHERE = {"ON_GROUND","IN_ROOM",},
	},
	ACTION = V_CLIMB_DOWN,
}
BUZZ("WALK", "GO", "RUN", "PROCEED", "STEP")
SYNTAX {
	VERB = "WAVE",
	OBJECT = {
		WHERE = {"HELD","CARRIED","TAKE","HAVE",},
	},
	ACTION = V_WAVE,
}
SYNTAX {
	VERB = "WAVE",
	OBJECT = {
		WHERE = {"HELD","CARRIED","TAKE","HAVE",},
	},
	JOIN = "AT",
	SUBJECT = {
	},
	ACTION = V_WAVE,
}
SYNTAX {
	VERB = "WAVE AT",
	OBJECT = {
	},
	ACTION = V_WAVE,
}
BUZZ("WAVE", "BRANDISH")
SYNTAX {
	VERB = "WEAR",
	OBJECT = {
	},
	ACTION = V_WEAR,
}
SYNTAX {
	VERB = "WIN",
	ACTION = V_WIN,
}
BUZZ("WIN", "WINNAGE")
SYNTAX {
	VERB = "WIND",
	OBJECT = {
	},
	ACTION = V_WIND,
}
SYNTAX {
	VERB = "WIND UP",
	OBJECT = {
	},
	ACTION = V_WIND,
}
SYNTAX {
	VERB = "WISH",
	ACTION = V_WISH,
}
SYNTAX {
	VERB = "YELL",
	ACTION = V_YELL,
}
BUZZ("YELL", "SCREAM", "SHOUT")
SYNTAX {
	VERB = "ZORK",
	ACTION = V_ZORK,
}
